### ISSUE TITLE
STRUMPACK fails on LLNL Lassen when building with CUDA

### ISSUE THREAD

**Issue by balos1** [xsdk-project/xsdk-issues#135]
Spack arch: `linux-rhel7-power9le`
Compiler: `gcc@7.3.1`
Command: 
```
spack install -j40 xsdk+cuda~dealii %gcc@7.3.1 ^spectrum-mpi@10.3.0.01rtm3  ^openblas@0.3.5 ^magma cuda_arch=70
```

Error: `nvcc fatal   : Unknown option 'pthread'`

[strumpack-spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5532269/strumpack-spack-build-out.txt)

**Comment by pghysels** [comment]
Seems like this is a known CMake issue that is fixed in newer CMake versions:
https://gitlab.kitware.com/cmake/cmake/-/issues/18008

I think adding this line:
`set(THREADS_PREFER_PTHREAD_FLAG FALSE)`
somewhere at the beginning of the CMakeLists.txt file will solve it.
But CMake documentation highly recommends leaving that switch set to TRUE.

I don't know whether I should make a new release for this?

**Comment by balos1** [comment]
> Seems like this is a known CMake issue that is fixed in newer CMake versions:
https://gitlab.kitware.com/cmake/cmake/-/issues/18008

I thought it could be that issue, however, this was built with CMake 3.18.0 so that bug should be solved.

**Comment by balos1** [comment]
@pghysels Must be this issue with 3.18.0 (similar to 18008): https://gitlab.kitware.com/cmake/cmake/-/issues/21108, which seems to be fixed in 3.18.2. I will try the build again with a different cmake version.

**Comment by balos1** [comment]
The build goes through fine with CMake@3.18.2 and should also be fine with CMake 3.13.0:3.17.x. Versions 3.18.0 and 3.18.1 seem to be the versions that are effected by the bug.

@balay Do we just want to note this in the install instructions, or should SLATE and STRUMPACK add conflicts (with cmake 3.18.0/3.18.1) to their spack packages?

**Comment by pghysels** [comment]
I also have this issue on my ubuntu with CMake 3.18.0 and 3.18.1.
I tried adding
`set(THREADS_PREFER_PTHREAD_FLAG FALSE)`
but that does not fix the problem.

**Comment by balos1** [comment]
@pghysels I think the issue comes from using the targets `MPI::MPI_<lang>` [here](https://github.com/pghysels/STRUMPACK/blob/d8ec8a8200f080ae4b4790f7e4d608cf27c2429a/CMakeLists.txt#L481) . You might be able to use the variables `${MPI_<lang>_LIBRARIES}` instead of the targets, at least when its a problematic CMake version, and I think that would solve the issue... at least this is how I solved the issue in SUNDIALS for CMake <= 3.13.0.
