### ISSUE TITLE
strumpack@master failure on various test boxes

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#150]
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1408088631
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1408088612
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1408088619
```
==> Error: OSError: No such file or directory: '/data/xsdkci/VS1mJQ1K/1/xsdk-project/spack-xsdk/spack-stage/balay/spack-stage-strumpack-master-53dfcgw6ydwqov5qaleb2zjobhkszhid/spack-src/examples/data'
```
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1408088626

A different error here?
```
/Users/xsdk/builds/cYLkqamb/0/xsdk-project/spack-xsdk/spack-stage/spack-stage-strumpack-master-3tpo2npulbqmqyycnlbtwwmkhsaiuykz/spack-src/src/structured/StructuredMatrixC.cpp:204:61: error: implicit conversion \
from '_Complex float' to 'float' is not permitted in C++
         [&A](int i, int j) -> std::complex<float> { return A(i,j); },
                                                            ^~~~~~
```
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/6785090/spack-build-out.txt)

Yesterday's build didn't have these issues
https://gitlab.com/xsdk-project/spack-xsdk/-/pipelines/332954700

**Comment by balay** [comment]
I'm still confused about the trigger for these 2 errros. I see some spack changes and a single strumpack change - but don't understand the relation to these 2 failures.

The first issue is due to a change in Apr - but why is it triggered now?
```
commit 851f4e3971d52c68153aa3e42e1f998a56f96a7d
Author: Pieter Ghysels <pghysels@lbl.gov>
Date:   Tue Apr 20 23:08:02 2021 -0700

    Reorder examples in sparse/ and dense/ folders

```
I have a potential fix: https://github.com/spack/spack/commit/045f324a9c65fc2a6b3d5ee22800e0362b590fbc

**Comment by pghysels** [comment]
The commit is from April, but I merged that branch yesterday.
I will look into it today.

Pieter

**Comment by balay** [comment]
Ok - I need to figure out if spack saves the commit for a build in logs - so its easier to look for the actual changes in the branch.

**Comment by pghysels** [comment]
I cannot reproduce this
`error: implicit conversion from '_Complex float' to 'float' is not permitted in C++`
I tried with a small test code, with different clang versions (9,11,12) and different C++ standards (98/11/14/17).
It seems related to this https://reviews.llvm.org/D35817

I did try to fix it here:
 https://github.com/pghysels/STRUMPACK/commit/967782df94c421cf6f460445070130a092439524
I hope that helps.

**Comment by balay** [comment]
@pghysels I'm still getting build errors. Attaching the log

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/6786884/spack-build-out.txt)

**Comment by pghysels** [comment]
Can you try again?
https://github.com/pghysels/STRUMPACK/commit/f51cd6bda69513ad03c040cb5fba087f03a4ed51
We tested on a Mac with clang, where we could reproduce the problem.

**Comment by balay** [comment]
Thanks! This MacOS build goes through now.
