### ISSUE TITLE
butterflypack failure with intel compilers

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#222]
I think this issue existed before with 0.8.0 - and butterflypack was disabled for this build.

Re-enabling (for 1.0.0) to recheck - I get failures. Here is the log.

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/12487915/spack-build-out.txt)

**Comment by liuyangzhuan** [comment]
Hi, Satish,
It seems to be related to unrecognized omp atomics with intel compilers. I've made a few fixes now and if you pass -Denable_openmp=OFF to cmake, openmp will be completely disabled. Can you give the latest commit (or the newly released version 2.3.1) a try?

**Comment by liuyangzhuan** [comment]
@balay Any follow-up on this?

**Comment by balay** [comment]
sorry for the delay.

Any idea how do I make this switch (automatically) in spack?

**Comment by liuyangzhuan** [comment]
So there should be a variant 
variant("openmp", default=True, description="add OpenMP support")
that you can turn off for intel related failure

Of course, you need to add 
version("2.3.1", sha256="26ddda76ccf014894a5a531e303cbea19ce8a2ad8ec438974f0443a5d6082101")

as well.

**Comment by balay** [comment]
I'm having to juggle intel compiler builds due to other failures [so don't have the exact prior setup to repeat].

One setup - I have a successful build - without any changes [with butterfly/master]
```
==> Installing butterflypack-2.3.0-4dnbcutrbqqh3xdepsw3yk6g2t57gnlr [83/125]
==> No binary for butterflypack-2.3.0-4dnbcutrbqqh3xdepsw3yk6g2t57gnlr found: installing from source
==> No patches needed for butterflypack
==> butterflypack: Executing phase: 'cmake'
==> butterflypack: Executing phase: 'build'
==> butterflypack: Executing phase: 'install'
==> butterflypack: Successfully installed butterflypack-2.3.0-4dnbcutrbqqh3xdepsw3yk6g2t57gnlr
  Stage: 50.12s.  Cmake: 25.22s.  Build: 24m 42.92s.  Install: 0.66s.  Post-install: 0.11s.  Total: 25m 59.26s
[+] /data/balay/spack.y/opt/spack/linux-rocky9-cascadelake/intel-19.1.1.217/butterflypack-2.3.0-4dnbcutrbqqh3xdepsw3yk6g2t57gnlr
```

Another setup - I get failures even with `~openmp` ( again with master) [I see its using ` '-Denable_openmp=OFF'`]

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/12610708/spack-build-out.txt)

Another build with failure:

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/12610946/spack-build-out.txt)

**Comment by balay** [comment]
BTW: perhaps a different issue: failure with clang

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/12610961/spack-build-out.txt)

**Comment by liuyangzhuan** [comment]
All the three failures you are seeing now is due to something like:

/home/xsdk/spack.y/spack-stage/spack-stage-butterflypack-2.3.0-hqhlkkwnhqreok7ndvhree3uees55euf/spack-src/EXAMPLE/FIO_Driver.cpp:779:27: error: no matching constructor for initialization of 'vector<_Complex double>'
  779 |   vector<_Complex double> xout1((nvec)*(myseg_n),{0.0,0.0});

I don't know if it's related to 
https://itecnote.com/tecnote/c-no-matching-constructor-for-initialization-of-vector-with-clang-3-2/

Any hint?

**Comment by liuyangzhuan** [comment]
According to the url, the fix would be to use an updated version of libstdc++ under at least C++11. I would imagine this will cause failures for several other xsdk packages as well.

**Comment by balay** [comment]
Sorry I don't know what changes I should use on my end to get these issues resolved. Right now the builds are with:

```
    version("2.3.0", branch="master")
```

i.e with master branch.

Will add in current build logs here.

**Comment by balay** [comment]
xr_l_c170-xsdk-100-linux-clang1700 

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5276299108

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/12885043/spack-build-out.txt)

**Comment by balay** [comment]
xr_l_i23-xsdk-100-linux-oneapi2023-2-0

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5276299105

Log in the artifacts above

**Comment by balay** [comment]
xr_l_i23-xsdk-100-linux-oneapi2023-1-0 

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5276299092

Log in the artifacts above

**Comment by balay** [comment]
xr_l_i22-xsdk-100-linux-oneapi202220

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5276299111

Log in the artifacts above

**Comment by liuyangzhuan** [comment]
@balay  I have pushed this commit 
https://github.com/liuyangzhuan/ButterflyPACK/commit/0e2b83ca470504abaf01ce228404711d42828d33
Can you give it a try? If it works, I can create a new release version.

**Comment by balay** [comment]
Thanks!

xr_l_i23-xsdk-100-linux-oneapi2023-2-0 is good now

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5285007527

xr_l_i23-xsdk-100-linux-oneapi2023-1-0 is also good

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5285007524

xr_l_i22-xsdk-100-linux-oneapi202220 has a *failure*

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5285007530

**Comment by liuyangzhuan** [comment]
Can you try the latest commit 
https://github.com/liuyangzhuan/ButterflyPACK/commit/91953463e0cc8434db0fd652b037b20d076dacbd

**Comment by balay** [comment]
I've started a new pipeline at 

~https://gitlab.com/xsdk-project/spack-xsdk/-/pipelines/1036328708~

 https://gitlab.com/xsdk-project/spack-xsdk/-/pipelines/1036334714

**Comment by balay** [comment]
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5291324292

The error persists.

I'm not sure why this intel build fails [while the other intel builds succeed]

**Comment by liuyangzhuan** [comment]
I recall that this is an error we encountered before in 
https://github.com/xsdk-project/xsdk-issues/issues/180
at that time for oneapi@2022.2.0, we saw the same error and we tried to use
butterflypack~openmp
to avoid that. 

Can you also use butterflypack~openmp for xr_l_i22-xsdk-100-linux-oneapi202220? 

If this resolves the issue, please let me know when I should pack a new release version.

**Comment by balay** [comment]
Ah sorry missed that one. I've added `butterflypack~openmp` to this CI build. Thanks!

[a manual run built successfully]

**Comment by balay** [comment]
@liuyangzhuan I've started seeing butterflypack failures with latest master branch - with intel compilers

https://gitlab.com/xsdk-project/spack-xsdk/-/pipelines/1055371190

I guess the last successful build was with:
```
commit 91953463e0cc8434db0fd652b037b20d076dacbd
Author: liuyangzhuan <liuyangzhuan@gmail.com>
Date:   Fri Oct 13 11:15:22 2023 -0700

    fixing omp atomic compile error for intel oneapi2022
```

Perhaps this snapshot should be tagged as a release?

**Comment by liuyangzhuan** [comment]
@balay I've fixed this error with the latest commit and packed a release v2.4.0 
https://github.com/liuyangzhuan/ButterflyPACK/releases/tag/v2.4.0

**Comment by balay** [comment]
thanks! updated xsdk-1.0.0 to use 2.4.0
